import type { BlindPost } from "../src/lib/x/audit-eval";

/** No model labels, weights, gate reasons or arm names are embedded here. */
export function reviewHtml(packet: (BlindPost & { reviewId: string })[], packetHash: string): string {
  const data = JSON.stringify(packet).replaceAll("<", "\\u003c").replaceAll("\u2028", "\\u2028").replaceAll("\u2029", "\\u2029");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blind lead review</title>
<style>
:root{color-scheme:light dark}body{margin:0;color:var(--foreground,light-dark(#182026,#eef1f4));font:14px/1.5 var(--font-sans,system-ui,sans-serif)}*{box-sizing:border-box}h2{font-size:20px;margin:0 0 6px}p{margin:6px 0 12px}.muted,small{color:var(--muted-foreground,light-dark(#566573,#a5afb8))}.panel{padding:16px;background:var(--card,light-dark(#f3f5f7,#20252b));border-radius:var(--radius,10px);margin:12px 0}pre{white-space:pre-wrap;font:inherit;margin:0;overflow-wrap:anywhere}label{display:block;margin:8px 0 4px;font-weight:550}input,select,textarea,button{font:inherit}input,select,textarea{width:100%;padding:9px;background:transparent;color:inherit;border:1px solid var(--border,light-dark(#d7dde3,#3e464e));border-radius:6px}textarea{min-height:60px;resize:vertical}button{padding:8px 12px;border:1px solid var(--border,light-dark(#d7dde3,#3e464e));border-radius:6px;color:inherit;background:transparent;cursor:pointer}button.primary{background:var(--primary,light-dark(#162633,#e2edf5));color:var(--primary-foreground,light-dark(#fff,#162633))}button:disabled{opacity:.4;cursor:default}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.row #progress{margin-left:auto}.error{color:var(--destructive,light-dark(#b72c27,#ff9990))}a{color:inherit}.facts{font-size:13px}.facts strong{display:block;margin-top:6px}[hidden]{display:none!important}.fields{display:grid;gap:6px;grid-template-columns:1fr 1fr}@media(max-width:520px){.fields{grid-template-columns:1fr}}:focus-visible{outline:2px solid var(--primary,light-dark(#162633,#e2edf5));outline-offset:2px}
</style></head><body>
<h2>Blind lead review</h2><p class="muted">Judge the post against the product facts. Buyer need and useful conversation are separate. Missing evidence belongs in “insufficient.” This deliberately selected packet is not a population precision sample.</p>
<label for="reviewer">Reviewer name</label><input id="reviewer" autocomplete="name" placeholder="Your name — required for export">
<div class="row" style="margin-top:12px"><button id="prev">Previous</button><button id="next">Next</button><span id="progress" aria-live="polite"></span></div>
<div class="panel"><div class="row"><strong id="product"></strong><span id="reviewId" class="muted"></span></div><div id="facts" class="facts"></div></div>
<div class="panel"><pre id="post"></pre><p class="muted" id="context"></p><a id="source" target="_blank" rel="noreferrer noopener">Open original post</a></div>
<label for="gold">Your verdict</label><select id="gold"><option value="">Choose a verdict</option><option value="ask">Buyer: current unresolved need, product demonstrably fits</option><option value="reply">Useful conversation: no evidenced buying intent</option><option value="not">Not relevant / promotion / already resolved</option><option value="insufficient">Insufficient evidence</option></select>
<label for="note">Why?</label><textarea id="note" placeholder="Explain your verdict from the supplied evidence."></textarea>
<div class="fields"><div id="needField"><label for="need">Exact author need</label><textarea id="need" placeholder="Quote the author's words"></textarea></div><div id="capabilityField"><label for="capability">Supported product capability</label><textarea id="capability" placeholder="Point to a supplied product fact, not a guess"></textarea></div><div id="unresolvedField"><label for="unresolved">Why is the need unresolved?</label><textarea id="unresolved"></textarea></div><div id="helpField"><label for="help">How does a product reply help?</label><textarea id="help"></textarea></div></div>
<p id="status" role="status" aria-live="polite"></p><div class="row"><button id="save" class="primary">Save verdict</button><button id="download">Download reviewed labels</button></div>
<p class="muted"><small>Drafts stay in this browser when local storage is available; otherwise keep the page open until you download. Download the JSONL to preserve your review. Nothing is submitted to Lurk, sent to X, or published. Product facts and post text are the saved audit context, not live verification.</small></p>
<script>
const packet=${data};
const storageKey='lurk-blind-review-${packetHash}';
const el=id=>document.getElementById(id);
let saved={};let index=0;
try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{}
el('reviewer').value=saved.reviewer||'';const drafts=saved.drafts||{};
const fields=['gold','note','need','capability','unresolved','help'];
function draft(){const row={};for(const f of fields)row[f]=el(f).value;drafts[packet[index].key]=row;persist()}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({reviewer:el('reviewer').value,drafts}))}catch{}}
function errorFor(row){if(!el('reviewer').value.trim())return 'Enter your reviewer name.';if(!row.gold)return 'Choose a verdict.';if(!row.note.trim())return 'Explain the verdict.';const required=row.gold==='ask'?['need','capability','unresolved','help']:row.gold==='reply'?['capability','help']:[];for(const f of required)if(!row[f].trim())return 'Add '+f+' evidence.';return null}
function visibility(){const gold=el('gold').value;for(const f of ['need','unresolved'])el(f+'Field').hidden=gold!=='ask';for(const f of ['capability','help'])el(f+'Field').hidden=gold!=='ask'&&gold!=='reply'}
function show(){const p=packet[index];el('product').textContent=p.product.name;el('reviewId').textContent=p.reviewId;el('facts').replaceChildren();for(const [label,value]of [['Product URL',p.product.url],['Pain',p.product.pain],['Solution',p.product.solution],['Target users',p.product.targetUsers]]){const h=document.createElement('strong');h.textContent=label;const v=document.createElement('div');v.textContent=value||'Not supplied';el('facts').append(h,v)}el('post').textContent=p.post.text;el('context').textContent=p.replyingTo?'Parent post by @'+p.replyingTo.author+': '+p.replyingTo.text:'';let source;try{source=new URL(p.post.url)}catch{};el('source').href=source&&source.protocol==='https:'&&source.hostname==='x.com'?source.href:'#';el('source').textContent='@'+p.post.author+' · '+p.post.created+' · open original';const row=drafts[p.key]||{};for(const f of fields)el(f).value=row[f]||'';visibility();el('prev').disabled=index===0;el('next').disabled=index===packet.length-1;const complete=packet.filter(p=>drafts[p.key]&&!errorFor(drafts[p.key])).length;el('progress').textContent=(index+1)+' / '+packet.length+' · '+complete+' complete';el('status').textContent='';el('status').className=''}
el('gold').onchange=visibility;
el('prev').onclick=()=>{draft();index=Math.max(0,index-1);show()};el('next').onclick=()=>{draft();index=Math.min(packet.length-1,index+1);show()};
el('reviewer').oninput=persist;
el('save').onclick=()=>{draft();const error=errorFor(drafts[packet[index].key]);if(error){el('status').textContent=error;el('status').className='error';return}show();el('status').textContent='Verdict saved locally.'};
el('download').onclick=()=>{draft();const rows=[];for(const p of packet){const row=drafts[p.key];if(!row||!row.gold)continue;const error=errorFor(row);if(error){el('status').textContent=p.reviewId+': '+error;el('status').className='error';return}rows.push({key:p.key,gold:row.gold,note:row.note,reviewer:el('reviewer').value.trim(),evidence:{need:row.need,capability:row.capability,unresolved:row.unresolved,help:row.help}})}if(!rows.length){el('status').textContent='No completed reviews to download.';return}const url=URL.createObjectURL(new Blob([rows.map(row=>JSON.stringify(row)).join('\\n')+'\\n'],{type:'application/x-ndjson'}));const a=document.createElement('a');a.href=url;a.download='adjudications.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);el('status').textContent=rows.length+' reviews downloaded.'};
if(packet.length)show();else el('status').textContent='No review cards.';
console.log('Blind packet loaded: '+packet.length+' cards; no arms, original verdicts, or selection weights embedded.');
</script></body></html>`;
}
